{
  "id": "eXo Platform",
  "viewports": [
    {
      "label": "desktop",
      "width": 1500,
      "height": 768
    }
  ],
  "scenarios": [
    {
      "label": "Login Page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onReady_login.js",
      "hideSelectors": ["div#loginFooter"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div.uiLogin"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Home Page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onReady_home.js",
      "hideSelectors": ["ul#suggestions li","div.currentDateContainer center a"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        ".LeftNavigationTDContainer.TDContainer",
        ".RightBodyTDContainer.TDContainer",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "td.OfficeMiddleTDContainer.TDContainer",
        "td.OfficeRightTDContainer.TDContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Apps Btn",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_appsbtn.js",
      "hideSelectors": ["ul#suggestions li","div.currentDateContainer center a"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Apps Page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_appspage.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Calendar Page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onReady_calendar.js",
      "hideSelectors": [],
      "removeSelectors": ["div#UIMiniCalendar","div.eventWeekBar"],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Add User Btn",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_adduserbtn.js",
      "hideSelectors": ["ul#suggestions li",".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div.UITableColumnContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Community_page_adduser",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_adduserpage.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div.UITableColumnContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "UserMgmntBtn",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usermgmntbtn.js",
      "hideSelectors": ["ul#suggestions li",".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div.UITableColumnContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "CommPage",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usermgmntpage.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div.UITableColumnContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "ContentBtn",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_contentbtn.js",
      "hideSelectors": ["ul#suggestions li",".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div.UITableColumnContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Content_admin",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_contentadminpage.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div.UITableColumnContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "ContentMgmnt",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_contentMgmnt.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div.UITableColumnContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Content_search_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_contentsearch.js",
      "hideSelectors": ["div.currentDateContainer center"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Documents_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_document.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Documents_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_docs.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Forums_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_forums_page.js",
      "hideSelectors": ["div#UICategoryInfo"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Network_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_network_page.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "PortalBtn",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_portalbtn.js",
      "hideSelectors": ["ul#suggestions li","div.currentDateContainer center a"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div.UITableColumnContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Portal_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_portalpage.js",
      "hideSelectors": ["div.currentDateContainer center"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div.UITableColumnContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Portal_gpsites_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_portalgpsitespage.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Portal_notifs_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_portalnotifspage.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Portal_sites_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_portalsitespage.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Portalpages_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_portalpages.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Searchindexing_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_searchindexinpage.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Spaces_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_spacespage.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "System_mngmnt_space",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_systemmanagespaces.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "System_mngmnt_space_templates_button",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_systemmanagespacestemplatesbutton.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Tasks_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_taskspage.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_acts",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpage_acts.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_flags",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpageflags.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer",
        "div.MaskContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Close_flags",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_closeflags.js",
      "hideSelectors": ["ul#suggestions li","div.currentDateContainer center a"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_network",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpagenetwork.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_notifs",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpagenotifs.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_settings",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpagesettings.js",
      "hideSelectors": ["ul#suggestions li","div.currentDateContainer center a"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Close_settings",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_closeusersettings.js",
      "hideSelectors": ["ul#suggestions li","div.currentDateContainer center a"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "WebconfBtn",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_webconfbtn.js",
      "hideSelectors": ["ul#suggestions li",".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Webconf_page",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_webconfpage.js",
      "hideSelectors": [".calendarPortlet"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_wiki",
      "url": "http://fqa02.exoplatform.org" ,
      "referenceUrl": "http://fqa01.exoplatform.org" ,
      "readyEvent": "",
      "readySelector": "",
      "delay": 2000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpagewiki.js",
      "hideSelectors": ["div.uiWikiPageInfoArea"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": 0,
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
     {
          "label": "Open Chat Button",
          "url": "http://fqa02.exoplatform.org" ,
          "referenceUrl": "http://fqa01.exoplatform.org" ,
          "readyEvent": "",
          "readySelector": "",
          "delay": 2000,
          "onBeforeScript": "",
          "onReadyScript": "onBefore_chatpage.js",
          "hideSelectors": [".calendarPortlet"],
          "removeSelectors": [],
          "hoverSelector": "",
          "clickSelector": "",
          "postInteractionWait": 0,
          "selectors": [
            "viewport",
            "document",
            "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
            "div#RightBody.UIContainer"
          ],
          "selectorExpansion": true,
          "misMatchThreshold" : 0,
          "requireSameDimensions": true
        },
           {
              "label": "User_page_profile",
              "url": "http://fqa02.exoplatform.org" ,
              "referenceUrl": "http://fqa01.exoplatform.org" ,
              "readyEvent": "",
              "readySelector": "",
              "delay": 2000,
              "onBeforeScript": "",
              "onReadyScript": "onBefore_usrpageprofile.js",
              "hideSelectors": [".calendarPortlet"],
              "removeSelectors": [],
              "hoverSelector": "",
              "clickSelector": "",
              "postInteractionWait": 0,
              "selectors": [
                "viewport",
                "document",
                "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
                "div#RightBody.UIContainer"
              ],
              "selectorExpansion": true,
              "misMatchThreshold" : 0,
              "requireSameDimensions": true
            }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data_desktop/bitmaps_reference",
    "bitmaps_test": "backstop_data_desktop/bitmaps_test",
    "engine_scripts": "backstop_data_desktop/engine_scripts",
    "html_report": "backstop_data_desktop/html_report",
    "ci_report": "backstop_data_desktop/ci_report"
  },
  "report": ["browser", "CI"],
  "engine": "phantomjs",
  "engineOptions": {
    "args": ["--no-sandbox"]
  },
  "asyncCaptureLimit": 5,
  "asyncCompareLimit": 50,
  "debug": false,
  "debugWindow": false,
  "casperflags":[],
  "cliExitOnFail":true
}
