module.exports = {
  "id": "eXo PLF Mobile",
  "viewports": [
    {
      "label": "mobile",
      "width": 320,
      "height": 480
    }
  ],

  "scenarios": [
    {
      "label": "Login_page",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 500,
      "hideSelectors": ["div#loginFooter"],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div.uiLogin"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Home_page",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 500,
      "onReadyScript": "onReady_home.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Answers_page",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onReadyScript": "onBefore_answers.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Calendar_page",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onReadyScript": "onReady_calendar.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "ChatButton",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "onBeforeScript": "",
      "onReadyScript": "onReady_chatbtn.js",
      "delay": 1000,
      "hideSelectors": ["div.currentDateContainer center"],
      "removeSelectors": [],
      "hoverSelector": "",      
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Chat_page",
      "url": "http://qa-ui03.exoplatform.org/portal/intranet/chat",
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/intranet/chat",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "hideSelectors": ["div.currentDateContainer center"],
      "removeSelectors": [],
      "hoverSelector": "",
      "onBeforeScript": "onBefore_chatpage.js",
      "onReadyScript": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",        
        "div.uiGrayLightBox.clearfix.input-prepend.no-user-selection",
        "div.uiLeftContainerArea.no-user-selection"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Documents_page",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onReadyScript": "onBefore_document.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    

    
    {
      "label": "Documents_page",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onReadyScript": "onBefore_docs.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Forums_page",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_forums_page.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Network_page",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_network_page.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Spaces_page",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_spacespage.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Tasks_page",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_taskspage.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_acts",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpage_acts.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_dashboard",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpagedashbrd.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_flags",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpageflags.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer",
        "div.MaskContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Close_flags",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_Closeflags.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_network",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpagenetwork.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_notifs",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpagenotifs.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_profile",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpageprofile.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_settings",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpagesettings.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer",
        "div.MaskContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "Close_settings",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_closeusersettings.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    },
    {
      "label": "User_page_wiki",
      "url": process.argv[process.argv.length-1],
      "referenceUrl": "http://qa-ui03.exoplatform.org/portal/login?initialURI=%2Fportal%2Fintranet%2F",
      "readyEvent": null,
      "readySelector": "",
      "delay": 1000,
      "onBeforeScript": "",
      "onReadyScript": "onBefore_usrpagewiki.js",
      "hideSelectors": [],
      "removeSelectors": [],
      "hoverSelector": "",
      "clickSelector": "",
      "postInteractionWait": "",
      "selectors": [
        "viewport",
        "document",
        "div#NavigationPortlet.UIContainer div.TRContainer.clearfix",
        "div#RightBody.UIContainer"
      ],
      "selectorExpansion": true,
      "misMatchThreshold" : 0,
      "requireSameDimensions": true
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data_mobile/bitmaps_reference",
    "bitmaps_test": "backstop_data_mobile/bitmaps_test",
    "engine_scripts": "backstop_data_mobile/engine_scripts",
    "html_report": "backstop_data_mobile/html_report",
    "ci_report": "backstop_data_mobile/ci_report"
  },
  "report": ["browser", "CI"],
  "engine": "phantomjs",
  "engineFlags": [],
  "asyncCaptureLimit": 5,
  "asyncCompareLimit": 50,
  "debug": false,
  "debugWindow": false,
  "casperflags":[],
  "cliExitOnFail":false,
  "port":3001
}