= UI Quality Assurance project for eXo Platform
:link-chrome-driver: https://chromedriver.storage.googleapis.com/2.28
:link-chrome-driver-notes: {link-chrome-driver}/notes.txt
:link-chrome-driver-linux32: {link-chrome-driver}/chromedriver_linux32.zip
:link-chrome-driver-linux64: {link-chrome-driver}/chromedriver_linux64.zip
:link-chrome-driver-mac64: {link-chrome-driver}/chromedriver_mac64.zip
:link-chrome-driver-win32: {link-chrome-driver}/chromedriver_win32.zip

Automation Process for Functional Tests on eXo Platform.

[IMPORTANT]
The whole documentation is availabe at https://github.com/exoplatform/platform-qa-ui-documentation

== Quick Start


. Start PLF instance
+
[source, shell]
----
$ docker-compose -f core/src/main/resources/stack/docker-compose-44-hsqldb.yml -p exo44hsqldb up

# Access to PLF instance
$ open http://localhost

# Access to Mail UI (all mails sent by eXo PLF)
$ open http://localhost/mail
----
+
. Configure your browser
.. Run tests with your local Browsers
... Chrome

* Download the *Chrome Driver* compatible with your OS ({link-chrome-driver-notes}[notes]):
** {link-chrome-driver-linux32}[Linux32] / {link-chrome-driver-linux64}[Linux64]
** {link-chrome-driver-mac64}[Mac64]
** {link-chrome-driver-win32}[Win32]
* Unzip it locally
** _ie: /tmp/chromedriver_

... Firefox
TODO
.. Run tests in headless Browsers
TODO
. Execute the UI Integration Tests from your IDE
.. Configure the test to *add the following System properties* in the `Run > Edit configurations... > VM options` input text +
 `-ea -Dwebdriver.chrome.driver=/tmp/chromedriver -Dselenide.baseUrl=http://localhost:80`
.. Run the test



~/opt/maven32/bin/mvn  clean verify -Prun-its -Dmaven.failsafe.debug="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 -Xnoagent -Djava.compiler=NONE" -Dremote=http://192.168.0.7:4444/wd/hub -Dbrowser=chrome

[source,shell]
.Run All in containers: test with Maven and Local Chrome
----
mvn  clean verify -Prun-its,chrome \
    -Dselenide.baseUrl=http://localhost:8080
----

.Run All in containers: test with Maven and Local Firefox
----
mvn  clean verify -Prun-its,firefox \
    -Dselenide.baseUrl=http://localhost:8080
----

.Debug on test tagged with @tag("debug")
----
mvn  clean verify -Prun-its,firefox \
    -Dselenide.test.tags.include=debug \
    -Dmaven.failsafe.debug="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 -Xnoagent -Djava.compiler=NONE" \
    -Dselenide.baseUrl=http://localhost:8080
----


[source,shell]
. Maven and Selenium Grid / Chrome
----
mvn  clean verify -Prun-its,grid \
    -Dselenide.baseUrl=http://localhost:8080 \
    -Dremote=http://localhost:4444/wd/hub \
    -Dselenide.browser=chrome  \
    -Dselenide.timeout=20000
----


[source,shell]
. Maven and Selenium Grid / Firefox
----
mvn  clean verify -Prun-its,grid \
    -Dselenide.test.tags.include=debug \
    -Dselenide.baseUrl=http://exo:8080 \
    -Dremote=http://localhost:4444/wd/hub \
    -Dselenide.browser=firefox  \
    -Dselenide.timeout=20000
----

[source,shell]
.Run All in containers: test with Maven and Selenium Grid
----
c-mvn  clean verify -Prun-its,grid \
    -Dselenide.baseUrl=http://exo:8080 \
    -Dremote=http://hub:4444/wd/hub \
    -Dselenide.browser=chrome  \
    -Dselenide.timeout=20000
----
