= UI Quality Assurance project for eXo Platform
:toc:
:toclevels: 4
:link-chrome-driver: https://chromedriver.storage.googleapis.com/2.28
:link-chrome-driver-notes: {link-chrome-driver}/notes.txt
:link-chrome-driver-linux32: {link-chrome-driver}/chromedriver_linux32.zip
:link-chrome-driver-linux64: {link-chrome-driver}/chromedriver_linux64.zip
:link-chrome-driver-mac64: {link-chrome-driver}/chromedriver_mac64.zip
:link-chrome-driver-win32: {link-chrome-driver}/chromedriver_win32.zip
:link-firefox-driver: https://github.com/mozilla/geckodriver/releases/download/v0.14.0
:link-firefox-driver-notes: https://github.com/mozilla/geckodriver/releases/tag/v0.14.0
:link-firefox-driver-linux32: {link-firefox-driver}/geckodriver-v0.14.0-linux32.tar.gz
:link-firefox-driver-linux64: {link-firefox-driver}/geckodriver-v0.14.0-linux64.tar.gz
:link-firefox-driver-mac64: {link-firefox-driver}/geckodriver-v0.14.0-macos.tar.gz
:link-firefox-driver-win32: {link-firefox-driver}/geckodriver-v0.14.0-win64.zip

Automation Process for Functional Tests on eXo Platform.

== Overview

Technical stacks required:

* Docker & Docker Compose 1.13+
* JUnit 5
* Selenide 4.2 (Selenium 3.0.1)
* Selenium Grid 3.0.1
* Maven 3.3.9

== Getting Started

=== PLF instance and Selenium Grid

[NOTE]
--
Actually we use :

* *PLF 4.4.0* ont Tomcat with HSQLDB database
* *Selenium Grid 3.0.1*
--

.Start PLF instance and Selenium Grid
[source, shell]
----
$ git clone git@github.com:exoplatform/platform-qa-ui.git
$ docker-compose -f core/src/main/resources/stack/docker-compose-44-hsqldb.yml -p qa_ui up

# Check that the PLF instance is running
$ open http://localhost:8080

# Check that the Selenium Grid is UP
$ open http://localhost:4444/grid/console
----


=== Drivers for Chrome and Firefox

[IMPORTANT]
--
Those drivers are required only to run UI tests with your local browsers.
If you want to execute the *tests with Selenium Grid, you can skip this step*.
--

==== Chrome Drivers

* Download the *Chrome Driver* compatible with your OS ({link-chrome-driver-notes}[notes]):
** {link-chrome-driver-linux32}[Linux32] / {link-chrome-driver-linux64}[Linux64]
** {link-chrome-driver-mac64}[Mac64]
** {link-chrome-driver-win32}[Win32]
* Unzip it locally
** _ie: /tmp/chromedriver_

==== Firefox (gecko) Drivers

* Download the *Firefox Driver* compatible with your OS ({link-chrome-firefox-notes}[notes]):
** {link-firefox-driver-linux32}[Linux32] / {link-firefox-driver-linux64}[Linux64]
** {link-firefox-driver-mac64}[Mac64]
** {link-firefox-driver-win32}[Win32]
* Unzip it locally
** _ie: /tmp/geckodriver_

=== Run UI Tests from your IDE

==== Configure IntellIJ IDEA

[IMPORTANT]
--
To be able to execute JUnit5 Tests with IntellIJ, you need at *least IntellIJ 2016.3*
--

. Configure the test to *add the following System properties* in the `Run > Edit configurations... > VM options` input text +
 `-ea -Dwebdriver.chrome.driver=/tmp/chromedriver -Dselenide.baseUrl=http://localhost:8080`
.. Run the test

=== Run UI Tests from Maven

==== Use the Selenium Grid

[source,shell]
.Maven and Selenium Grid / Chrome
----
mvn  clean verify -Prun-its,grid \
    -Dselenide.baseUrl=http://exo:8080 \
    -Dremote=http://localhost:4444/wd/hub \
    -Dselenide.browser=chrome  \
    -Dselenide.timeout=20000
----

[source,shell]
.Maven and Selenium Grid / Firefox
----
mvn  clean verify -Prun-its,grid \
    -Dselenide.baseUrl=http://exo:8080 \
    -Dremote=http://localhost:4444/wd/hub \
    -Dselenide.browser=firefox  \
    -Dselenide.timeout=20000
----

==== Use your local browsers

[IMPORTANT]
--
Be sure to have your drivers configured, you can override the default path with Maven system variables:

* Firefox: `-Dselenium.webdriver.geckodriver.driver.path=<path-to-driver`
* Chrome: `-Dselenium.webdriver.chrome.driver.path=<path-to-driver`
--

[source,shell]
.Run with Maven and Local Chrome
----
mvn  clean verify -Prun-its,chrome \
    -Dselenide.baseUrl=http://localhost:8080
----

[source,shell]
.Run with Maven and your local Firefox
----
mvn  clean verify -Prun-its,firefox \
    -Dselenide.baseUrl=http://localhost:8080
----

=== Debug

[source,java]
----
@Test
@Smoke
@Tag("smoke")
@Tag("debug") // <1>
public void test01_CheckHomePage() {
  info("Test 1: Check Home page");
...
}
----
<1> Tag a test with `@Tag("debug")`

.Debug one test tagged with @tag("debug")
[source,shell]
----
mvn  clean verify -Prun-its,firefox \
    -Dselenide.test.tags.include=debug \
    -Dmaven.failsafe.debug="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 -Xnoagent -Djava.compiler=NONE" \
    -Dselenide.baseUrl=http://localhost:8080
----


=== Run UI Tests from Maven in Container

[IMPORTANT]
--
*c-maven* is an alias to run Maven in Docker *connected to the the network qa_ui*
--

[source,shell]
.Run All in containers: test with Maven and Selenium Grid
----
c-mvn  clean verify -Prun-its,grid \
    -Dselenide.baseUrl=http://exo:8080 \
    -Dremote=http://hub:4444/wd/hub \
    -Dselenide.browser=chrome  \
    -Dselenide.timeout=20000
----
