= UI Quality Assurance project for eXo Platform
:toc:
:toclevels: 4
:link-chrome-driver: https://chromedriver.storage.googleapis.com/2.28
:link-chrome-driver-notes: {link-chrome-driver}/notes.txt
:link-chrome-driver-linux32: {link-chrome-driver}/chromedriver_linux32.zip
:link-chrome-driver-linux64: {link-chrome-driver}/chromedriver_linux64.zip
:link-chrome-driver-mac64: {link-chrome-driver}/chromedriver_mac64.zip
:link-chrome-driver-win32: {link-chrome-driver}/chromedriver_win32.zip
:link-firefox-driver: https://github.com/mozilla/geckodriver/releases/download/v0.14.0
:link-firefox-driver-notes: https://github.com/mozilla/geckodriver/releases/tag/v0.14.0
:link-firefox-driver-linux32: {link-firefox-driver}/geckodriver-v0.14.0-linux32.tar.gz
:link-firefox-driver-linux64: {link-firefox-driver}/geckodriver-v0.14.0-linux64.tar.gz
:link-firefox-driver-mac64: {link-firefox-driver}/geckodriver-v0.14.0-macos.tar.gz
:link-firefox-driver-win32: {link-firefox-driver}/geckodriver-v0.14.0-win64.zip

Automation Process for Functional Tests on eXo Platform.

== Overview

Technical stacks required:

* Docker & Docker Compose 1.13+
* JUnit 5
* Selenide 4.2 (Selenium 3.0.1)
* Selenium Grid 3.0.1
* Maven 3.3.9

== Getting Started

=== PLF instance and Selenium Grid

[NOTE]
--
Actually we use :

* *PLF 5.2.0-Mxx*
* *Selenium Grid 3.11.0*
--

.Start PLF instance, Selenium Grid and MailHog
[source, shell]
----
$ git clone git@github.com:exoplatform/platform-qa-ui.git
$ docker-compose -f core/src/main/resources/stack/docker-compose-50-hsqldb.yml -p qa_ui up

# Check that the PLF instance is running
$ open http://localhost:8080

# Check that the Selenium Grid is UP
$ open http://localhost:4444/grid/console

# Check that MailHog is UP
$ open http://localhost:8025/mail/
----


=== Drivers for Chrome and Firefox

[IMPORTANT]
--
Those drivers are required only to run UI tests with your local browsers.
If you want to execute the *tests with Selenium Grid, you can skip this step*.
--

==== Chrome Drivers

* Download the *Chrome Driver* compatible with your OS ({link-chrome-driver-notes}[notes]):
** {link-chrome-driver-linux32}[Linux32] / {link-chrome-driver-linux64}[Linux64]
** {link-chrome-driver-mac64}[Mac64]
** {link-chrome-driver-win32}[Win32]
* Unzip it locally
** _ie: /tmp/chromedriver_

==== Firefox (gecko) Drivers

* Download the *Firefox Driver* compatible with your OS ({link-chrome-firefox-notes}[notes]):
** {link-firefox-driver-linux32}[Linux32] / {link-firefox-driver-linux64}[Linux64]
** {link-firefox-driver-mac64}[Mac64]
** {link-firefox-driver-win32}[Win32]
* Unzip it locally
** _ie: /tmp/geckodriver_

=== Run UI Tests from your IDE

==== Configure IntellIJ IDEA

[IMPORTANT]
--
To be able to execute JUnit5 Tests with IntellIJ, you need at *least IntellIJ 2018.x*
--

. Configure the test to *add the following System properties* in the `Run > Edit configurations... > VM options` input text +
 `-ea -Dwebdriver.chrome.driver=/tmp/chromedriver -Dselenide.baseUrl=http://localhost:8080`
.. Run the test

=== Run UI Tests from Maven

==== Use browsers in a Selenium Grid

To launch a local Selenium Grid you just need to launch it with the compose file at the root of this repository :

[source,shell]
.Launch Selenium Grid 01
----
docker-compose -f docker-compose-selenium-grid01.yml -p grid01 up -d
----

This will launch 1 Selenium Grid on the local port `4401` with 1 Chrome node and 1 Firefox node

You can then launch your Maven Automated tests on Chrome or Firefox with one of the following command:

[source,shell]
.Maven tests with Chrome through Selenium Grid 01
----
mvn  clean verify -Prun-its,grid \
    -Dselenide.baseUrl=http://exo:8080 \
    -Dremote=http://localhost:4401/wd/hub \
    -Dselenide.browser=chrome  \
    -Dselenide.timeout=20000
----

[source,shell]
.Maven tests with Firefox through Selenium Grid 01
----
mvn  clean verify -Prun-its,grid \
    -Dselenide.baseUrl=http://exo:8080 \
    -Dremote=http://localhost:4401/wd/hub \
    -Dselenide.browser=firefox  \
    -Dselenide.timeout=20000
----

[NOTE]
----
You can also launch more Selenium Grid on your local environment to be able to launch more maven tests in parallel.
For that we provide 3 different Compose files which use different local ports. When started you just have to be careful in your maven launch command to use the good local port in the `-Dremote=http://localhost:<GRID_PORT>/wd/hub`.
----

|===
|Start Command |Selenium Grid local port

|docker-compose -f docker-compose-selenium-hub01.yml -p grid01 up
| `-Dremote=http://localhost:4401/wd/hub`

|docker-compose -f docker-compose-selenium-hub02.yml -p grid02 up
| `-Dremote=http://localhost:4402/wd/hub`

|docker-compose -f docker-compose-selenium-hub03.yml -p grid03 up
| `-Dremote=http://localhost:4403/wd/hub`
|===


==== Use your local browsers

[IMPORTANT]
--
Be sure to have your drivers configured, you can override the default path with Maven system variables:

* Firefox: `-Dselenium.webdriver.geckodriver.driver.path=<path-to-driver`
* Chrome: `-Dselenium.webdriver.chrome.driver.path=<path-to-driver`
--

[source,shell]
.Run with Maven and Local Chrome
----
mvn  clean verify -Prun-its,chrome \
    -Dselenide.baseUrl=http://localhost:8080
----

[source,shell]
.Run with Maven and your local Firefox
----
mvn  clean verify -Prun-its,firefox \
    -Dselenide.baseUrl=http://localhost:8080
----

=== Debug

[source,java]
----
@Test
@Smoke
@Tag("smoke")
@Tag("debug") // <1>
public void test01_CheckHomePage() {
  info("Test 1: Check Home page");
...
}
----
<1> Tag a test with `@Tag("debug")`

.Debug one test tagged with @tag("debug")
[source,shell]
----
mvn  clean verify -Prun-its,firefox \
    -Dselenide.test.tags.include=debug \
    -Dmaven.failsafe.debug="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 -Xnoagent -Djava.compiler=NONE" \
    -Dselenide.baseUrl=http://localhost:8080
----


=== Run UI Tests from Maven in Container

[IMPORTANT]
--
*mvncw* is an alias to run Maven in Docker *connected to the the network qa_ui*
--

[source,shell]
.Run All in containers: test with Maven and Selenium Grid
----
mvncw  clean verify -Prun-its,grid \
    -Dselenide.baseUrl=http://exo:8080 \
    -Dremote=http://hub:4444/wd/hub \
    -Dselenide.browser=chrome  \
    -Dselenide.timeout=20000
----

== Data for sniff tests

Data for sniff tests, such as Office documents or images, are stored in https://github.com/exoplatform/platform-qa-ui-data[a dedicated Github repository].
These data are included in the project `platform-qa-ui` thanks to https://git-scm.com/docs/git-submodule[Git submodules].

All data pushed in the project `platform-qa-ui-data` are available in the folder `platform/src/test/resources/data` of the project `platform-qa-ui`, 
with the same path.
For example the file `forum/topic_attachment.txt` of the project `platform-qa-ui-data` is available 
at `platform/src/test/resources/data/forum/topic_attachment.txt` in the project `platform-qa-ui`.

=== Getting started

The first time the submodule is used (after a git clone for example), the submodule must be initialized.
Run the following commands at the root level of the project `platform-qa-ui`:
[source,shell]
----
git submodule init
git submodule update
----

You should now see the data files in the folder `platform/src/test/resources/data`.

=== How to add new files ?

The parent project is not aware of changes done in the submodule project automatically.
Each time new files are pushed in the submodule project, an update must be explicitly done on parent project.

NOTE: It is important to understand that the link between the parent project and the submodule is based on a *commit id*,
not on a branch or a tag. And this commit id in stored in the git index files of parent project.
So if new files are committed and pushed in the submodule project, if nothing is done on parent project and
if you run again a `git submodule update`, new files will not come up.
You have to add the option `--remote` to fetch the latest changes of the submodule.

So here is how you basically add new files and use them:

* commit new files in the project `platform-qa-ui-data`
* in the project `platform-qa-ui`, at the root level, run
[source,shell]
----
git submodule update --remote
----

At this point, you should see the new files from `platform-qa-ui-data`.
You will notice that the working dir in not clean anymore, there are some uncommitted changes. Example:

$ git status
On branch feature/external-data-sets
Your branch is up-to-date with 'origin/feature/external-data-sets'.
[source,shell]
----
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   platform/src/test/resources/data (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
----

Since we pulled the latest changes from the branch and not from the linked commit id of the submodule,
the commits ids are not the same, which explains the status message.
You must commit these changes (you probably want to do it as part of the fix/improvements you are working on). 

=== How to add new files in branches/PR ?

If you want to add new files as part of new branches/PR, the new branch must be created in both project and the submodule configuration must be updated.
Here are the steps to follow:

* in the project `platform-qa-ui-data`, create the new branch and push it:
[source,shell]
----
git checkout -b new-branch
git push -u origin new-branch
----
* create any new files and push them

* in the project `platform-qa-ui`, create the new branch and push it:
[source,shell]
----
git checkout -b new-branch
git push -u origin new-branch
----
* update the value of branch attribute in the file `.gitmodules` with the name of the new branch:
[source,shell]
----
[submodule "platform/src/test/resources/data"]
        path = platform/src/test/resources/data
        url = git@github.com:exoplatform/platform-qa-ui-data.git
        branch = new-branch
----
WARNING: do not commit and push that change. It is only used during the branch life and must not be merged in master branch.
* update the submodule:
[source,shell]
----
git submodule update --remote
----