#
# Copyright (C) 2003-2017 eXo Platform SAS.
#
# This file is part of eXo PLF:: QA - UI - API.
#
# eXo PLF:: QA - UI - API is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 3 of
# the License, or (at your option) any later version.
#
# eXo PLF:: QA - UI - API software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with eXo PLF:: QA - UI - API; if not, write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA, or see <http://www.gnu.org/licenses/>.
#

version: '2'
services:
  web:
    image: nginx:1.10-alpine
    expose:
      - "80"
    volumes:
      - ./conf/nginx-plf44.conf:/etc/nginx/nginx.conf:ro
    networks:
      - front
      - mail
  exo:
    image: exoplatform/exo:4.4.1_0
    environment:
      EXO_DB_NAME: exo
      EXO_DB_USER: exo
      EXO_DB_PASSWORD: exo
      EXO_DB_HOST: db
      EXO_DB_POOL_IDM_INIT_SIZE: 1
      EXO_DB_POOL_IDM_MAX_SIZE: 10
      EXO_DB_POOL_JCR_INIT_SIZE: 2
      EXO_DB_POOL_JCR_MAX_SIZE: 5
      EXO_DB_POOL_JPA_INIT_SIZE: 3
      EXO_DB_POOL_JPA_MAX_SIZE: 20
      EXO_PROXY_VHOST: localhost
      EXO_PROXY_SSL: "false"
      EXO_JVM_SIZE_MIN: "2g"
      EXO_JVM_SIZE_MAX: "3g"
      EXO_MAIL_SMTP_HOST: "mail"
      EXO_MAIL_SMTP_PORT: "1025"
      EXO_JODCONVERTER_PORTS: "2002"
    expose:
      - "8080"
    networks:
      - front
      - back
      - mail
  mongo:
    image: mongo:3.2
    networks:
      - back
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: exo
      MYSQL_USER: exo
      MYSQL_PASSWORD: exo
    networks:
      - back
  pgsql:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_DB: exo
      POSTGRES_USER: exo
      POSTGRES_PASSWORD: exo
    networks:
      - back
  es:
    image: exoplatform/elasticsearch:0.3
    networks:
      - back
  mail:
    image: mailhog/mailhog
    environment:
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_STORAGE: mongodb
      MH_MONGO_URI: mongo:27017
      MH_MONGO_DB: mailhog
      MH_MONGO_COLLECTION: messages
      MH_UI_WEB_PATH: mail
    networks:
      - back
      - mail
