#
# Copyright (C) 2003-2017 eXo Platform SAS.
#
# This file is part of eXo PLF:: QA - UI - API.
#
# eXo PLF:: QA - UI - API is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 3 of
# the License, or (at your option) any later version.
#
# eXo PLF:: QA - UI - API software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with eXo PLF:: QA - UI - API; if not, write to the Free
# Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
# 02110-1301 USA, or see <http://www.gnu.org/licenses/>.
#

version: '2'
services:
  web:
    extends:
      file: common-plf50-stack.yml
      service: web
    ports:
      - "80:80"
    links:
      - exo
    depends_on:
      - exo
      - mail
  exo:
    extends:
      file: common-plf50-stack.yml
      service: exo
    container_name: exo
    environment:
      EXO_DB_TYPE: hsqldb
      EXO_ADDONS_LIST:
      EXO_ES_EMBEDDED: "true"
    ports:
      - "8080:8080"
      # (Linux) open JMX ports for local connection only
      #- "127.0.0.1:10001:10001"
      #- "127.0.0.1:10002:10002"
      # (macOS / Windows) open JMX ports on the host
      - "10001:10001"
      - "10002:10002"
    links:
      - mongo
    depends_on:
      - mongo
      - mail
  mongo:
    extends:
      file: common-plf50-stack.yml
      service: mongo
  mail:
    extends:
      file: common-plf50-stack.yml
      service: mail
    depends_on:
      - mongo
  selenium_hub:
    container_name: hub
    image: 'selenium/hub:3.0.1'
    ports:
    - '4444:4444'
    networks:
      - front
  selenium_node:
    image: 'selenium/node-firefox:3.0.1'
    depends_on:
      - selenium_hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium_hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1
    networks:
      - front
  selenium_node_chrome:
    image: 'selenium/node-chrome:3.0.1'
    depends_on:
      - selenium_hub
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium_hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 5
      NODE_MAX_INSTANCES: 5
    networks:
      - front
networks:
  front:
  back:
  mail:
