package org.exoplatform.platform.qa.ui.platform.ecms;
import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Selenide.*;
import static org.exoplatform.platform.qa.ui.selenium.Utils.getRandomNumber;
import static org.exoplatform.platform.qa.ui.selenium.locator.NavigationToolBarLocator.ELEMENT_LINK_EDIT;
import static org.exoplatform.platform.qa.ui.selenium.locator.ecms.ECMSLocator.*;
import static org.exoplatform.platform.qa.ui.selenium.locator.gatein.GateinLocator.*;
import static org.exoplatform.platform.qa.ui.selenium.logger.Logger.info;
import org.junit.Assert;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import com.codeborne.selenide.Condition;
import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.Selenide;
import org.exoplatform.platform.qa.ui.commons.Base;
import org.exoplatform.platform.qa.ui.core.PLFData;
import org.exoplatform.platform.qa.ui.ecms.pageobject.CreateNewDocument;
import org.exoplatform.platform.qa.ui.ecms.pageobject.SEOManagement;
import org.exoplatform.platform.qa.ui.ecms.pageobject.SiteExplorerHome;
import org.exoplatform.platform.qa.ui.gatein.pageobject.*;
import org.exoplatform.platform.qa.ui.selenium.platform.HomePagePlatform;
import org.exoplatform.platform.qa.ui.selenium.platform.ManageLogInOut;
import org.exoplatform.platform.qa.ui.selenium.platform.NavigationToolbar;
import org.exoplatform.platform.qa.ui.selenium.platform.administration.ChangeLanguages;
@Tag("ecms")
@Tag("sniff")
public class EcmsWCMTestIT extends Base {
  NavigationToolbar    navigationToolbar;
  SiteExplorerHome     siteExplorerHome;
  CreateNewDocument    createNewDocument;
  PageCreationWizard   pageCreationWizard;
  PortalManageSites    portalManageSites;
  PortalManagePages    portalManagePages;
  NavigationManagement navigationManagement;
  ManageLogInOut       manageLogInOut;
  ContentList          contentList;
  ChangeLanguages      changeLanguages;
  SEOManagement        seoManagement;
  HomePagePlatform     homePagePlatform;
  @BeforeEach
  public void setupBeforeMethod() {
    info("Start setUpBeforeMethod");
    navigationToolbar = new NavigationToolbar(this);
    siteExplorerHome = new SiteExplorerHome(this);
    createNewDocument = new CreateNewDocument(this);
    pageCreationWizard = new PageCreationWizard(this);
    portalManageSites = new PortalManageSites(this);
    portalManagePages = new PortalManagePages(this);
    navigationManagement = new NavigationManagement(this);
    contentList = new ContentList(this);
    changeLanguages = new ChangeLanguages(this);
    seoManagement = new SEOManagement(this);
    homePagePlatform = new HomePagePlatform(this);
    manageLogInOut = new ManageLogInOut(this);
    manageLogInOut.signInCas(PLFData.DATA_USER1, "gtngtn");
  }
  @Test
  @Tag("eabis")
  public void test01_CreateNewContentListViewerPageWithModeByContentsThenEditSingleContentViewerPage() {
    info("Create new Content List Viewer page with mode By Contents");
    String content = "content" + getRandomNumber();
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.goToPath("intranet", "Site Management");
    // Create node
    siteExplorerHome.goToAddNewContent();
    createNewDocument.createNewDoc(CreateNewDocument.selectDocumentType.WEBCONTENT);
    createNewDocument.addNewWebContent(content, content);
    createNewDocument.saveAndClose();
    siteExplorerHome.verifyContentCreatedSuccessfully(content);
    navigationToolbar.goToAddPage();
    pageCreationWizard.inputPageInfoStep1(content, true, "English", content, true, false);
    sleep(Configuration.timeout);
    $(ELEMENT_ADDNEWPAGE_BTNNEXT).waitUntil(Condition.visible,Configuration.timeout).click();
    $(ELEMENT_ADDNEWPAGE_BTNNEXT).waitUntil(Condition.visible,Configuration.timeout).click();
    sleep(2000);
    pageCreationWizard.addApplication($(ELEMENT_APPLICATION_CONTENT_TAB), $(byId("Content/ContentListViewerPortlet")));
    pageCreationWizard.addContentListByContent("General Drives/Sites Management/intranet", content);
    navigationToolbar.goToEditContent();
    ($(byXpath("(//a[contains(text(),'${content}')]/following::a[text()='Read more'])[1]".replace("${content}",content.substring(0,11))))).waitUntil(Condition.visible,Configuration.timeout).click();
    ELEMENT_LIST_CONTENT.find(byText(content)).waitUntil(Condition.visible, Configuration.timeout);
    info("Show draft/public content from page");
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.selectNode(content);
    siteExplorerHome.goToPublication();
    siteExplorerHome.changeStatusPulication("Published");
    navigationToolbar.goToUnEditContent();
    info("Delete Data test");
    info("Delete created file");
    sleep(2000);
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.deleteData(content, true);
    info("Delete created page");
    navigationToolbar.goToPotalPages();
    portalManagePages.deletePage(content, "");
    info("Show draft/public content from page");
    String content1 = "content" + getRandomNumber();
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.goToPath("intranet", "Site Management");
    // Create node
    siteExplorerHome.goToAddNewContent();
    createNewDocument.createNewDoc(CreateNewDocument.selectDocumentType.WEBCONTENT);
    createNewDocument.addNewWebContent(content1, content1);
    createNewDocument.saveAndClose();
    siteExplorerHome.verifyContentCreatedSuccessfully(content1);
    navigationToolbar.goToAddPage();
    pageCreationWizard.inputPageInfoStep1(content1, true, "English", content1, true, false);
    $(ELEMENT_ADDNEWPAGE_BTNNEXT).waitUntil(Condition.visible,Configuration.timeout).click();
    $(ELEMENT_ADDNEWPAGE_BTNNEXT).waitUntil(Condition.visible,Configuration.timeout).click();
    pageCreationWizard.addContentDetail("General Drives/Sites Management/intranet", content1);
    navigationToolbar.goToEditContent();
    ELEMENT_LIST_CONTENT.find(byText(content1)).waitUntil(Condition.visible, Configuration.timeout);
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.selectNode(content1);
    siteExplorerHome.goToPublication();
    siteExplorerHome.changeStatusPulication("Published");
    navigationToolbar.goToUnEditContent();
    info("Delete Data test");
    info("Delete created file");
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.deleteData(content1, true);
    info("Delete created page");
    navigationToolbar.goToPotalPages();
    portalManagePages.deletePage(content1, "");
    info("Edit Single Content Viewer page");
    String title0 = "title" + getRandomNumber();
    String content01 = "content1" + getRandomNumber();
    String content02 = "content2" + getRandomNumber();
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.goToPath("intranet", "Site Management");
    info("Create webcontent 1");
    sleep(2000);
    siteExplorerHome.goToAddNewContent();
    createNewDocument.createNewDoc(CreateNewDocument.selectDocumentType.WEBCONTENT);
    createNewDocument.addNewWebContent(content01, content01);
    createNewDocument.saveAndClose();
    siteExplorerHome.verifyContentCreatedSuccessfully(content01);
    info("Select acme folder");
    siteExplorerHome.selectNode("intranet");
    info("Create webcontent2");
    siteExplorerHome.goToAddNewContent();
    createNewDocument.createNewDoc(CreateNewDocument.selectDocumentType.WEBCONTENT);
    createNewDocument.addNewWebContent(content02, content02);
    createNewDocument.saveAndClose();
    siteExplorerHome.verifyContentCreatedSuccessfully(content02);
    navigationToolbar.goToAddPage();
    pageCreationWizard.inputPageInfoStep1(title0, true, "English", title0, true, false);
    $(ELEMENT_ADDNEWPAGE_BTNNEXT).waitUntil(Condition.visible,Configuration.openBrowserTimeoutMs).click();
    $(ELEMENT_ADDNEWPAGE_BTNNEXT).waitUntil(Condition.visible,Configuration.openBrowserTimeoutMs).click();
    pageCreationWizard.addContentDetail("General Drives/Sites Management/intranet", content1);
    $(byTitle("Portlet Mode")).click();
    $(byTitle("Edit")).click();
    sleep(Configuration.timeout);
    contentList.selectFolderContent("intranet", content02);
    sleep(Configuration.timeout);
    executeJavaScript("window.scrollBy(0,-350);", "");
    $(byText("Done")).waitUntil(Condition.appears, Configuration.timeout);
    info("Delete created files");
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.deleteData(content1, true);
    $(byText(content02)).waitUntil(Condition.appears, Configuration.timeout);
    siteExplorerHome.deleteData(content02, true);
    info("Delete create page");
    navigationToolbar.goToPotalPages();
    portalManagePages.deletePage(title0, "group");
  }
  @Test
  @Tag("eabis")
  public void test02_EditContentListViewerPageWithModeByContents() {
    info("Edit Content List Viewer page with mode By Contents");
    String title = "title" + getRandomNumber();
    String content1 = "content1" + getRandomNumber();
    String content2 = "content2" + getRandomNumber();
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.goToPath("intranet", "Site Management");
    info("Create webcontent1");
    siteExplorerHome.goToAddNewContent();
    createNewDocument.createNewDoc(CreateNewDocument.selectDocumentType.WEBCONTENT);
    createNewDocument.addNewWebContent(content1, content1);
    createNewDocument.saveAndClose();
    siteExplorerHome.verifyContentCreatedSuccessfully(content1);
    info("Select acme folder");
    siteExplorerHome.selectNode("intranet");
    info("Create webcontent2");
    siteExplorerHome.goToAddNewContent();
    createNewDocument.createNewDoc(CreateNewDocument.selectDocumentType.WEBCONTENT);
    createNewDocument.addNewWebContent(content2, content2);
    createNewDocument.saveAndClose();
    siteExplorerHome.verifyContentCreatedSuccessfully(content2);
    navigationToolbar.goToAddPage();
    pageCreationWizard.inputPageInfoStep1(title, true, "English", title, true, false);
    $(ELEMENT_ADDNEWPAGE_BTNNEXT).waitUntil(Condition.visible, Configuration.timeout).click();
    $(ELEMENT_ADDNEWPAGE_BTNNEXT).waitUntil(Condition.visible, Configuration.timeout).click();
    pageCreationWizard.addApplication($(ELEMENT_APPLICATION_CONTENT_TAB), $(byId("Content/ContentListViewerPortlet")));
    pageCreationWizard.addContentlistByFolder("General Drives/Sites Management", "intranet");
    navigationToolbar.goToEditContent();
    // Verify that all webcontents are shown in Content list View page
    ELEMENT_LIST_CONTENT.find(byText(content1)).waitUntil(Condition.visible, Configuration.timeout);
    ELEMENT_LIST_CONTENT.find(byText(content2)).waitUntil(Condition.visible, Configuration.timeout);
    $(ELEMENT_EDIT_CLV).hover();
    $(ELEMENT_EDIT_PREFERENCE).click();
    check(ELEMENT_CONTENT_LIST_BY_CONTENT_MODE, 2);
    contentList.selectFolderContent("General Drives/Sites Management/intranet", content1);
    $(ELEMENT_MULTIPLE_CONTENT_POPUP_SAVE_BTN).click();
    $(ELEMENT_CONTENT_LIST_PREFERENCE_SAVE_BTN).click();
    // Verify that all webcontents are shown in Content list View page
    $(byXpath(ELEMENT_CONTENT_LIST_CONTENT_TITLE.replace("${title}", content1))).waitUntil(Condition.visible,
            Configuration.timeout);
    $(byXpath(ELEMENT_CONTENT_LIST_CONTENT_TITLE.replace("${title}", content2))).waitUntil(Condition.not(Condition.visible),
            Configuration.timeout);
    info("Delete create files");
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.deleteData(content1, true);
    siteExplorerHome.deleteData(content2, true);
    info("Delete created page");
    navigationToolbar.goToPotalPages();
    portalManagePages.deletePage(title, "");
    info("Edit Content List viewer page with mode By Folder");
    String title1 = "title" + getRandomNumber();
    String content01 = "content0" + getRandomNumber();
    String content02 = "content0" + getRandomNumber();
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.goToPath("intranet", "Site Management");
    info("Create webcontent1");
    siteExplorerHome.goToAddNewContent();
    createNewDocument.createNewDoc(CreateNewDocument.selectDocumentType.WEBCONTENT);
    createNewDocument.addNewWebContent(content01, content01);
    createNewDocument.saveAndClose();
    siteExplorerHome.verifyContentCreatedSuccessfully(content01);
    info("Select acme folder");
    siteExplorerHome.selectNode("intranet");
    info("Create webcontent2");
    siteExplorerHome.goToAddNewContent();
    createNewDocument.createNewDoc(CreateNewDocument.selectDocumentType.WEBCONTENT);
    createNewDocument.addNewWebContent(content02, content02);
    createNewDocument.saveAndClose();
    siteExplorerHome.verifyContentCreatedSuccessfully(content02);
    navigationToolbar.goToAddPage();
    pageCreationWizard.inputPageInfoStep1(title1, true, "English", title1, true, false);
    $(ELEMENT_ADDNEWPAGE_BTNNEXT).click();
    $(ELEMENT_ADDNEWPAGE_BTNNEXT).click();
    pageCreationWizard.addApplication($(ELEMENT_APPLICATION_CONTENT_TAB), $(byId("Content/ContentListViewerPortlet")));
    pageCreationWizard.addContentListByContent("General Drives/Sites Management/intranet", content01);
    $(ELEMENT_LINK_EDIT).waitUntil(Condition.visible, Configuration.openBrowserTimeoutMs).click();
    $(byXpath("(//*[@id='UIAdminToolbarContainer']//a)[2]")).waitUntil(Condition.visible,Configuration.openBrowserTimeoutMs).click();
    navigationToolbar.goToEditContent();
    ELEMENT_LIST_CONTENT.find(byText(content01)).waitUntil(Condition.visible, Configuration.timeout);
    ELEMENT_LIST_CONTENT.find(byText(content02)).waitUntil(Condition.not(Condition.visible), Configuration.timeout);
    $(ELEMENT_EDIT_CLV).hover();
    $(ELEMENT_EDIT_PREFERENCE).click();
    check(ELEMENT_CONTENT_LIST_BY_FOLDER_MODE, 2);
    contentList.selectFolderContent("General Drives/Sites Management", "intranet");
    click(ELEMENT_CONTENT_LIST_PREFERENCE_SAVE_BTN);
    ELEMENT_LIST_CONTENT.find(byText(content01)).waitUntil(Condition.visible, Configuration.timeout);
    ELEMENT_LIST_CONTENT.find(byText(content02)).waitUntil(Condition.visible, Configuration.timeout);
    info("Delete created files");
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.deleteData(content01, true);
    siteExplorerHome.deleteData(content02, true);
    info("Delete created page");
    navigationToolbar.goToPotalPages();
    portalManagePages.deletePage(title1, "");
  }
  @Test
  public void test03_ManageTheTitleThenCheckSeoToolTips() {
    info("Manage the title");
    String title = "title" + getRandomNumber();
    navigationToolbar.goToSEO();
    $(ELEMENT_SEO_TITLEBOX).waitUntil(Condition.visible,Configuration.openBrowserTimeoutMs).setValue(title);
    $(ELEMENT_SEO_SAVE).waitUntil(Condition.visible,Configuration.openBrowserTimeoutMs).click();
    $(ELEMENT_SEO_CLOSE).waitUntil(Condition.visible,Configuration.openBrowserTimeoutMs).click();
    refresh();
    // Verify that the title of the page is changed
    Assert.assertEquals(Selenide.title(),title);
    navigationToolbar.goToSEO();
    $(byClassName("uiIconDelete")).waitUntil(Condition.visible,Configuration.openBrowserTimeoutMs).click();
    switchTo().alert().accept();
    $(ELEMENT_SEO_SAVE).waitUntil(Condition.visible,Configuration.openBrowserTimeoutMs).click();
    $(ELEMENT_SEO_CLOSE).waitUntil(Condition.visible,Configuration.openBrowserTimeoutMs).click();
    refresh();
    info("Check SEO tool tips");
    navigationToolbar.goToSEO();
    ELEMENT_SEO_HELPDESC.hover();
    $(ELEMENT_SEO_HELP_POPOVER).waitUntil(Condition.visible, Configuration.timeout);
    $(ELEMENT_SEO_HELPKEYWORD).hover();
    $(ELEMENT_SEO_HELP_POPOVER).waitUntil(Condition.visible, Configuration.timeout);
    $(ELEMENT_SEO_HELPPRIORITY).hover();
    $(ELEMENT_SEO_HELP_POPOVER).waitUntil(Condition.visible, Configuration.timeout);
    $(ELEMENT_SEO_CLOSE).click();
  }
  @Test
  @Tag("eabis")
  public void test04_AddThenUpdateSEOMetadasWithLocalization() {
    info("Add SEO metadas with localization");
    String title0 = "title" + getRandomNumber();
    String language01 = "French";
    info("language1 is:" + language01);
    String apply01 = "Apply";
    String language02 = "English";
    info("language2 is:" + language02);
    String apply02 = "Appliquer";
    navigationToolbar.goToSEO();
    $(ELEMENT_SEO_LANGUAGE_SHOW).click();
    $(ELEMENT_SEO_LANGUAGE_SELECTBOX).selectOption(language02);
    $(ELEMENT_SEO_TITLEBOX).setValue(title0);
    $(ELEMENT_SEO_SAVE).click();
    $(ELEMENT_SEO_CLOSE).click();
    refresh();
    navigationToolbar.goToChangeLanguage();
    changeLanguages.changeLanguage(language01, apply01);
    navigationToolbar.goToChangeLanguage();
    changeLanguages.changeLanguage(language02, apply02);
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.goToPath("intranet/SEO", "Site Management");
    // Verify that sitemaps is created in SEO folder
    $(byXpath(ELEMENT_SE_NODE.replace("${node}", "sitemaps"))).waitUntil(Condition.visible, Configuration.timeout);
    info("Delete SEO folder");
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.goToPath("intranet/SEO", "Site Management");
    siteExplorerHome.deleteData("SEO");
    homePagePlatform.goToHomePage();
    info("Detete added language on SEO management");
    navigationToolbar.goToSEO();
    seoManagement.deleteLanguage(language01);
    info("Update SEO metadatas with localization");
    String title = "title" + getRandomNumber();
    String language1 = "French";
    info("language1 is:" + language1);
    String apply1 = "Apply";
    String language2 = "English";
    info("language2 is:" + language2);
    String apply2 = "Appliquer";
    navigationToolbar.goToSEO();
    $(ELEMENT_SEO_LANGUAGE_SHOW).waitUntil(Condition.visible,Configuration.collectionsTimeout).click();
    $(ELEMENT_SEO_LANGUAGE_SELECTBOX).selectOption(language1);
    $(ELEMENT_SEO_TITLEBOX).setValue(title);
    $(ELEMENT_SEO_SAVE).waitUntil(Condition.visible,Configuration.collectionsTimeout).click();
    $(ELEMENT_SEO_CLOSE).waitUntil(Condition.visible,Configuration.collectionsTimeout).click();
    refresh();
    navigationToolbar.goToChangeLanguage();
    changeLanguages.changeLanguage(language1, apply1);
    navigationToolbar.goToChangeLanguage();
    info("Changed language is:" + language2);
    changeLanguages.changeLanguage(language2, apply2);
    // Verify that sitemaps file is updated
    $(byText("sitemaps")).waitUntil(Condition.visible, Configuration.timeout);
    info("Delete SEO folder");
    navigationToolbar.goToSiteExplorer();
    siteExplorerHome.goToPath("intranet/SEO", "Site Management");
    siteExplorerHome.deleteData("SEO");
    homePagePlatform.goToHomePage();
    navigationToolbar.goToSEO();
    seoManagement.deleteLanguage(language1);
  }
}
